// Generated by wrangler types (cf-typegen)
// Run: pnpm cf-typegen

interface Env {
  DB: D1Database;
  
  SITE_URL: string;
  WORKER_URL: string;
  
  DISCORD_CLIENT_ID: string;
  DISCORD_CLIENT_SECRET: string;
  DISCORD_GUILD_ID: string;
  DISCORD_KOFI_ROLE_ID: string;
  DISCORD_BOT_TOKEN: string;
  DISCORD_PUBLIC_KEY: string;
  DISCORD_APPROVAL_CHANNEL_ID: string;
  
  BETTER_AUTH_SECRET: string;
  
  MUX_TOKEN_ID: string;
  MUX_TOKEN_SECRET: string;
  MUX_SIGNING_KEY_ID: string;
  MUX_SIGNING_KEY_PRIVATE: string;
  
  KOFI_USERNAME: string;
  KOFI_VERIFICATION_TOKEN: string;
}
